# Zirconium-89 ion source with half-life of 78.41 hrs

# -------------------------------------------------------------
# Source Geometry
# -------------------------------------------------------------
#/gate/source/addSource				point Extended
#/gate/source/point/gps/type			Volume
#/gate/source/point/gps/shape			Sphere
#/gate/source/point/gps/radius			0.1 mm
#/gate/source/point/gps/angtype			iso

/gate/source/addSource twogamma
/gate/source/twogamma/setActivity 37000. becquerel 
/gate/source/twogamma/setType backtoback
/gate/source/twogamma/gps/particle gamma
/gate/source/twogamma/gps/energytype Mono
/gate/source/twogamma/gps/monoenergy 0.511 MeV
/gate/source/twogamma/gps/angtype iso
/gate/source/twogamma/gps/type Point

#/gate/source/addSource                          point

#/gate/source/point/gps/particle                 e+
#/gate/source/point/gps/energytype               Mono
#/gate/source/point/setType                      backtoback

#/gate/source/point/gps/monoenergy               395. keV
#/gate/source/point/setForcedUnstableFlag        true
#/gate/source/point/setForcedHalfLife            282276 s    # 78.41 hrs or 3.267 days
#/gate/source/point/setActivity                  10.0 MBq    # Literature says activity typically used for Zr-89 can range from 37-74 MBq

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Cannot get Zr-89 to work as defined below. Defined above as gamma particle.
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#/gate/source/point/gps/particle                 ion
#/gate/source/point/gps/ion                      40 89 0 0
#/gate/source/point/gps/monoenergy               0. keV
#/gate/source/point/setActivity                  20.0 kBq
#/gate/source/point/setForcedUnstableFlag        true
#/gate/source/point/setForcedHalfLife            282276 s
#/gate/source/point/setType                      pPs
#/gate/source/point/useDefaultHalfLife
#/gate/source/point/setEnableDeexcitation        true
#/gate/source/point/setPromptGammaEnergy         909. keV

#/gate/source/addSource                          point Extended
#/gate/source/point/setActivity                  40 MBq
#/gate/source/point/gps/pos/centre               0. 0. 0. cm
#/gate/source/point/setForcedUnstableFlag        true
#/gate/source/point/setForcedHalfLife            282276 s
#/gate/source/point/setType                      pPs
#/gate/source/point/setEnableDeexcitation        true
#/gate/source/point/setPromptGammaEnergy         909. keV
#/gate/source/point/setPositroniumFraction       pPs 0.28
#/gate/source/point/gps/ene/mono                 511. keV

#/gate/source/addSource                          point Extended
#/gate/source/point/setActivity                  20 kBq
#/gate/source/point/gps/pos/centre               0. 0. 0. cm
#/gate/source/point/setType                      sg
#/gate/source/point/setEnableDeexcitation        false
#/gate/source/point/setEmissionEnergy            909 keV
