#----------------------------
# adder and readout
#----------------------------
/gate/digitizer/Singles/insert           adder
/gate/digitizer/Singles/insert           readout
/gate/digitizer/Singles/readout/setDepth 2 # scinBlock

#----------------------------
# Energy blurring
#----------------------------
/gate/digitizer/Singles/insert                        blurring
/gate/digitizer/Singles/blurring/setResolution        0.02
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV

#----------------------------
# Threshold & Uphold 
#----------------------------
/gate/digitizer/Singles/insert                   thresholder
/gate/digitizer/Singles/thresholder/setThreshold 491. keV
/gate/digitizer/Singles/insert                   upholder
/gate/digitizer/Singles/upholder/setUphold       531. keV

#----------------------------
# Time resolution
#----------------------------
/gate/digitizer/Singles/insert                           timeResolution
/gate/digitizer/Singles/timeResolution/setTimeResolution 8. ns

#----------------------------
# Coincidence
#----------------------------
/gate/digitizer/Coincidences/setWindow           16. ns
/gate/digitizer/Coincidences/MultiplesPolicy     takeWinnerOfGoods
/gate/digitizer/Coincidences/minSectorDifference 1

#/gate/digitizer/name            delay
#/gate/digitizer/insert          coincidenceSorter
#/gate/digitizer/delay/setWindow 0. ns
#/gate/digitizer/delay/setOffset 0. ns
#/gate/digitizer/delay/MultiplesPolicy takeWinnerOfGoods

